# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build the docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Declare the Python requirements required to build the documentation
python:
  install:
    - method: pip
      path: .
    - packages:
      - sphinx
      - myst-parser

# Custom build command to use the makefile
commands:
  - make -C docs html
