[project]
name = "pbeis"
description = "PyBaMM EIS"
requires-python = ">=3.9"
license = {file = "LICENSE.md"}
dynamic = ["version", "readme"]
dependencies = [
    "pybamm @ git+https://github.com/pybamm-team/PyBaMM.git@088ca3827c831e1b93c4667b6f4353f64fb32cbf",
    "matplotlib",
]

[tools.setuptools]
packages = [
    { include = "pbeis" },
]

[tool.setuptools.dynamic]
version = {attr = "pbeis.version.__version__"}
readme = {file = ["README.md"], content-type = "text/markdown"}
